duolicious/duolicious-frontend

App.tsx, components/in-depth-screen.tsx, components/profile-card.tsx, components/prospect-profile-screen.tsx, units/units.tsx
Stuff that still doesn't work in prospect profiles:
* Blocking + Reporting
* Hiding
* Viewing Q&A answers
=> Wire-up some prospect profile data

components/default-flat-list.tsx, components/in-depth-screen.tsx, components/location-selector.tsx, components/option-screen.tsx, components/otp-input.tsx, components/traits-tab.tsx, components/welcome-screen.tsx
* Closes https://github.com/duolicious/duolicious-backend/issues/21
* Closes #31
* Closes #32
* Closes #14
=> Easy tasks

components/button/option.tsx, components/inbox-tab.tsx, components/profile-tab.tsx, data/option-groups.tsx, xmpp/xmpp.tsx
* Closes #34
* Closes #35
* Closes #36
=> Misc fixes

components/quiz-card-stack.tsx, components/quiz-tab.tsx, components/traits-tab.tsx, data/gag-locations.tsx
Relates to https://github.com/duolicious/duolicious-frontend/issues/43
=> Fix traits refresh and add a gag location

.github/workflows/publish.yml, App.tsx, api/api.tsx, app.config.ts, components/utility-screen.tsx, data/gag-utility-notices.tsx, env/env.tsx, util/util.tsx
=> Utility notices

components/profile-tab.tsx, components/welcome-screen.tsx
such fun
much regulations
wow
---
Closes #62
=> Replace CTAs with terms and conditions

components/conversation-screen.tsx, components/prospect-profile-screen.tsx, components/welcome-screen.tsx, xmpp/xmpp.tsx
=> Block and report

components/option-screen.tsx
=> Add OTP countdown

components/profile-card.tsx, components/prospect-profile-screen.tsx, components/quiz-card-stack.tsx, events/events.tsx
Follow-up to #84. I forgot to handle profiles in Q&A search.
=> Immediately hide blocked or hidden 2

components/conversation-screen.tsx, components/inbox-tab.tsx, components/prospect-profile-screen.tsx, components/top-nav-bar-button.tsx, hide-and-block/hide-and-block.tsx, xmpp/xmpp.tsx
* Update inbox immediately upon block/hide
* Add menu to conversations which lets users hide/report others
* Make profile "block" button pop navigation to top
* Added "archived" to some phrases in the inbox
=> Misc improvements to hiding/blocking

App.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/24
=> Make the browser back button work

components/default-flat-list.tsx, components/inbox-item.tsx, components/inbox-tab.tsx, components/tab-bar.tsx, xmpp/xmpp.tsx
Other inbox tweaks:
* Sort intros by match percentage by default
* s/Unavailable User/Unavailable Person/
* Count inbox/archive messages correctly. (Affects inbox indicator and number of messages displayed in inbox tabs)
=> Hide/message buttons for intros (+ other inbox tweaks)

api/queue.tsx, components/profile-tab.tsx, components/quiz-card.tsx, components/tab-bar.tsx
* Closes https://github.com/duolicious/duolicious-frontend/issues/101
* Closes https://github.com/duolicious/duolicious-frontend/issues/105
* Closes https://github.com/duolicious/duolicious-frontend/issues/106
=> Misc issues

components/prospect-profile-screen.tsx, components/quiz-tab.tsx
=> Issues #132 and #131

components/inbox-tab.tsx, kv-storage/inbox.tsx
Partly addresses https://github.com/duolicious/duolicious-frontend/issues/135.
=> Store inbox tab settings in local storage

components/default-flat-list.tsx, components/in-depth-screen.tsx, components/prospect-profile-screen.tsx, components/quiz-card.tsx
=> Random bugs

App.tsx, api/api.tsx, components/avatar.tsx, components/conversation-screen.tsx, components/default-flat-list.tsx, components/in-depth-screen.tsx, components/inbox-item.tsx, components/inbox-tab.tsx, components/profile-card.tsx, components/profile-tab.tsx, components/prospect-profile-screen.tsx, components/quiz-card-stack.tsx, components/report-modal.tsx, components/search-filter-screen.tsx, components/tab-bar.tsx, data/option-groups.tsx, hide-and-block/hide-and-block.tsx, xmpp/xmpp.tsx
Closes #150
Closes #143 
Closes #142
Closes #96
Closes #51
Backend PR: https://github.com/duolicious/duolicious-backend/pull/193
=> Big chat changes

components/button/option.tsx, components/inbox-tab.tsx, components/profile-tab.tsx, components/prospect-profile-screen.tsx, components/search-filter-screen.tsx, data/option-groups.tsx
* Added icons to buttons
* Slightly improved some copy
* set `maxIntros = 20`
=> UX improvements

units/units.tsx
=> Fix: Height slider allows 5'12"

components/conversation-screen.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/201
=> Reverted conversation scroll changes from #200

components/default-flat-list.tsx, components/search-tab.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/166
=> Handle timeouts, HTTP 5xx in search results

components/prospect-profile-screen.tsx
Fixes an issue introduced by #205.
=> Show avatar on blank profiles

data/option-groups.tsx
=> Make deletion screen case-insensitive

app.config.ts
Related: https://github.com/duolicious/duolicious-frontend/pull/225
=> Version code 2

app.config.ts, components/conversation-screen.tsx, package-lock.json, package.json
=> Conversation screen: text area is too small

App.tsx
This reverts commit 70f47b146d55efc4f49bf1d3137f99df239b25d2.
=> Revert "Update stats again (#257)"

components/profile-tab.tsx, components/prospect-profile-screen.tsx
Implements ability to preview your profile. Just simply views your profile as you would anyone elses, and hides a couple things if you're seeing your own. Tested on web
Closes https://github.com/duolicious/duolicious-frontend/issues/264
Relates to https://github.com/duolicious/duolicious-frontend/issues/137
=> Allow previewing your own profile

api/api.tsx, components/welcome-screen.tsx
Simply add status to the api response and update a state to include the error message
closes #283
=> New login error messages

api/api.tsx, components/welcome-screen.tsx
=> New login error messages (#288)

components/inbox-tab.tsx, components/profile-tab.tsx, data/option-groups.tsx, xmpp/xmpp.tsx
Even after this PR, old conversations are still kind of glitched because I couldn't edit some JIDs stored in binary blobs in the DB and it seems to be confusing MongooseIM lol
=> Restore messages

App.tsx, kv-storage/navigation-state.tsx, xmpp/xmpp.tsx
Remembers the last tab, works pretty simply - store the nav state after each navigation, load it as the initial state on mount. I went through mostly everything and don't see any issues. I did not test it on android/mobile, only on web (chrome).
Test cases: Test each screen, being in menus, chats, refreshing a new/empty chat, profiles, options (e.g. editing search filter), etc, logging in/out, or any other screens/things not mentioned. Refresh in each and observe no errors. 
There was an issue with the chat screen, as it kind of assumed the home page would be loaded first, so it has time to connect before you go to chats. If you loaded directly into a chat, it would instantly try to fetch messages, but at that point its not connected yet, and it would break the page. So I've added a …
=> Remember last tab

App.tsx, kv-storage/navigation-state.tsx, xmpp/xmpp.tsx
=> Remember last tab (#274)

App.tsx, components/conversation-screen.tsx, components/images.tsx, components/profile-tab.tsx, scales/scales.tsx
Closes #292
Closes #304
Closes #306
=> Misc mobile improvements

App.tsx, components/profile-card.tsx, components/prospect-profile-screen.tsx, components/welcome-screen.tsx
=> Avoid prospect profile redraws

eas.json, package-lock.json, package.json
* Fixes issues which prevent iOS builds
=> Version 13 for iOS

App.tsx, components/club-selector.tsx, components/option-screen.tsx, components/profile-tab.tsx, components/search-filter-screen.tsx, components/search-tab.tsx, data/option-groups.tsx, package-lock.json, package.json
Closes: https://github.com/duolicious/duolicious-frontend/issues/332 - This arguably doesn't completely satisfy this ticket. For many reasons, some users suggested a group chat feature. For example, some users feel pressured by the requirement to have one-on-one conversations with strangers. Some users like to observe prospective matches' behavior to others first, to provide more certainty the prospective match is being genuine during one-on-one conversations.
Closes: https://github.com/duolicious/duolicious-frontend/issues/315 - Increases the limit to 100.
=> Make it easier to search by club

App.tsx, components/club-selector.tsx, components/search-tab.tsx, events/events.tsx
=> Remember club search preference

components/club-selector.tsx, components/pinchy.tsx, components/profile-tab.tsx, components/traits-tab.tsx, data/option-groups.tsx
* Clarify verification instructions
* Change the size and color of some spinners, especially on iOS
=> Misc UI improvements

components/conversation-screen.tsx
* Made the logic the same across web and mobile
* Avoided fetching the first page twice on mobile
=> Change message fetching logic

components/donation-nag-modal.tsx
This will just be temporary because the current modal was rushed into production. The modal should be improved to nag a bit less aggressively, and also to update the countdown timer automatically.
=> Disable donation nag modal

components/donation-nag-modal.tsx
Reverts duolicious/duolicious-frontend#399
Now that https://github.com/duolicious/duolicious-backend/pull/487 is done, this can be reverted
=> Revert "Disable donation nag modal"

xmpp/xmpp.tsx
* Delete dead code
* Fix issue where messages from one user appear as many conversations in the inbox
=> XMPP cleaning

app.config.ts, components/conversation-screen.tsx, eas.json, package-lock.json, package.json
* Deployed to Android
* Not deployed to iOS
=> Version 19

components/otp-input.tsx
Related: #411
Related: #406
Related: #364
=> Remind onboardees to check spam

components/otp-input.tsx
Reverts duolicious/duolicious-frontend#416
=> Revert "Remind onboardees to check spam"

components/default-text-input.tsx, components/default-text.tsx, components/keyboard-dismissing-view.tsx, components/option-screen.tsx, components/otp-input.tsx, components/profile-card.tsx, components/welcome-screen.tsx, data/option-groups.tsx, package-lock.json, package.json
This also fixes a bug in iOS where users can't scroll the inputs in an option screen. In fact, most of this PR is to fix that issue.
This might not look very good on Android devices whose vendors use custom emojis (e.g. Samsung). The smiley face and pinkie emojis might overlap. I also haven't tested on Windows.
=> Explain verification pose more clearly

components/profile-tab.tsx
Related: https://github.com/duolicious/duolicious-backend/pull/491
=> 'Export Data' button

components/conversation-screen.tsx, components/inbox-tab.tsx, components/invite.tsx, components/q-and-a-device.tsx, components/search-filter-screen.tsx, components/search-tab.tsx, components/top-nav-bar-button.tsx
=> Make search filter buttons more prominent

app.config.ts, kv-storage/kv-storage.tsx, package-lock.json, package.json
• Added the ability to change your display name
• Added the ability to export your data
• Fixes and improvements to onboarding
• The conversation screen is a bit prettier
=> Version 22

components/profile-card.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/439
=> Fix blank blurhashes on private profiles

animation/animation.tsx, club/club.tsx, components/basic.tsx, components/club-selector.tsx
=> I forgot a commit

app.config.ts, package-lock.json, package.json
• Now you can join a club by pressing it on someone else's profile
• The installation size is a bit smaller
=> Version 23

api/queue.tsx, data/option-groups.tsx
The front end definitely needs better tests
=> Fix sign-in/sign-up bugs

components/prospect-profile-screen.tsx
This will make it possible to remove stats from the mobile version without having to release a new app.
=> Conditional rendering of stats

components/conversation-screen.tsx
Fix https://github.com/duolicious/duolicious-frontend/issues/466
=> Clear stale conversation history

components/prospect-profile-screen.tsx
closes https://github.com/duolicious/duolicious-frontend/issues/476
=> Audio bio rough edges

components/audio-bio.tsx
=> Play audio clips in silent mode

components/default-flat-list.tsx, components/profile-card.tsx, components/search-tab.tsx
The shitness seems restricted to Android. I'll urgently push an update because the shitness is quite pronounced
=> Work around the fact that expo-image is shit

app.config.ts, package-lock.json, package.json
• Added verification badges to messages in your inbox
• Added a message explaining that rude intros can't be sent
• Made profile stats more legible
=> Version 26

xmpp/xmpp.tsx
Ideally, this'd be done server-side but I don't know how to do that, so I'm doing it on the client. Here's a ticket: https://github.com/duolicious/duolicious-backend/issues/543
=> Unset push token on upon logout

app.config.ts, components/otp-input.tsx, package-lock.json, package.json
=> Version 27

App.tsx, components/prospect-profile-screen.tsx, kv-storage/navigation-state.tsx, navigation/navigation.tsx
Related: https://github.com/duolicious/duolicious-frontend/issues/137. I'm not sure this PR closes it though, because that ticket suggests allowing brave users to make their profiles public.
=> Profile URLs

components/prospect-profile-screen.tsx
=> Disable autoplaying voice bios

App.tsx, components/conversation-screen.tsx, components/default-flat-list.tsx, components/inbox-tab.tsx, components/navigation/scroll-bar-hooks.tsx, components/navigation/scroll-bar.tsx, components/navigation/tab-bar.tsx, components/navigation/util.tsx, components/navigation/web-bar.tsx, components/navigation/web-navigator.tsx, components/profile-tab.tsx, components/prospect-profile-screen.tsx, components/q-and-a-device.tsx, components/quiz-card.tsx, components/search-tab.tsx, components/top-nav-bar-button.tsx, components/top-nav-bar.tsx, components/traits-tab.tsx
Looks like this on web (mobile is unaffected):
---
=> Web UI refresh

components/conversation-screen.tsx
=> Autogrow chat input

api/api.tsx, components/conversation-screen.tsx, components/profile-tab.tsx, package-lock.json, package.json, xmpp/xmpp.tsx
Safety features tend to improve the gender ratio. While safety features are mostly implemented server-side, this PR adds messages to explain why users, for example, had their rude profile blocked.
=> Safety enhancements

app.config.ts, components/conversation-screen.tsx, components/prospect-profile-screen.tsx, package-lock.json, package.json
• Safety: Unverified users can send fewer daily intros than verified users
• Safety: Rude phrases and spammy content in display names and in self summaries are automatically blocked while editing profiles
=> Version 28

components/images/images.tsx
Seems like this make a race condition less likely, but it doesn't seem like a very good fix.
=> Kind of fix #562

components/conversation-screen.tsx, components/message-divider.tsx, util/util.tsx
e21c6df has modifications to #560. They're mostly style changes.
=> Deepesh kalura deepesh kalura/issue320

package-lock.json, package.json, patches/@react-navigation+core+7.3.1.patch
Related: https://github.com/react-navigation/react-navigation/issues/12399
=> Remove `deepFreeze` in dev

app.config.ts, package-lock.json, package.json
• Hold and drag your profile's photos to reorder them
• Dividers appear between messages when there's more than a day between them
• Bug fixes
=> Version 29

components/images/images.tsx
=> Photo layout goes wonky when display name changes its height

components/images/images.tsx
Reverts duolicious/duolicious-frontend#577
=> Revert "Photo layout goes wonky when display name changes its height"

components/images/images.tsx
=> Reduce renders during image dragging

components/images/images.tsx, events/events.tsx
=> Fix: Dragging photos is slow on Android

app.config.ts, package-lock.json, package.json
• Bug fixes and performance improvements when customizing profile photos
=> Version 29.0.1

components/base-quiz-card.tsx, components/prospect-profile-screen.tsx, package-lock.json, package.json
=> Remove dependency: `@react-spring/native`

components/inbox-tab.tsx, xmpp/xmpp.tsx
* Fixes #590
* Fixes a regression introduced by #587 where the inbox fails to update when a message is sent or received
=> Chat fixes

app.config.ts, package-lock.json, package.json
• Safety: Fix an issue where the report modal doesn't appear in some cases
• UX/UI: Bug fixes and performance improvements
=> Version 29.0.2

app.config.ts, package-lock.json, package.json
• Bug fixes and performance improvements when answering Q&A
=> Version 29.0.3

.github/workflows/type-checking.yml, .github/workflows/type-checks.yml, README.md, components/color-picker-modal/hue-picker.tsx, components/default-flat-list.tsx, components/navigation/scroll-bar.tsx, components/navigation/util.tsx, components/prospect-profile-screen.tsx, package-lock.json, package.json, verification/verification.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/297
=> Type checking in CI

app.config.ts, package-lock.json, package.json
• Fix share URL on 'Traits' tab
=> Version 29.0.4

xmpp/xmpp.tsx
In some places it assumed `from` being a uuid, in others it could handle it being a personId too.
This caused messages, if they were sufficiently old, to appear to be sent by the other party, when they were yours.
=> fix: unify checking of message being from the current user

components/auto-resizing-gif.tsx, components/speech-bubble.tsx
=> Require tapping on a gif to load it

app.config.ts, components/conversation-screen.tsx, components/profile-tab.tsx, package-lock.json, package.json
• Add shareable Tenor GIFs to chat
• Bug fixes
=> Version 29.1.0

components/modal/gif-picker-modal.tsx
=> Higher resolution gif previews on non-mobile clients

components/check-box.tsx
=> Increase `hitSlop` for checkbox

App.tsx, components/modal/donation-nag-modal.tsx
=> Prevent donation screen reappearing when dismissed

components/speech-bubble.test.tsx, components/speech-bubble.tsx
=> Markdown support for quotes

app.config.ts, package-lock.json, package.json
• Add missing attribution to Tenor GIFs
• Other bug fixes and improvements
=> Version 29.1.1

components/profile-card.tsx
Profile cards are now more like regular links, allowing them to be opened in new tabs on web.
Closes: #632
=> feat: allow opening profiles in new tab

components/profile-card.tsx
Hopefully counteracts some of the flickering from #660
=> Reduce profile flickering

App.tsx, components/modal/donation-nag-modal.tsx
=> Try to fix the donation nag modal again

components/labelled-slider.tsx
Reverts duolicious/duolicious-frontend#670
=> Revert "Fix issue with restoring state"

app.config.ts, package-lock.json, package.json
• Bug fixes and performance improvements
---
=> Version 29.1.2

app.config.ts, package-lock.json, package.json
=> Version 29.1.3

components/avatar.tsx, components/profile-card.tsx, util/navigation.tsx
=> feat: allow opening profiles on q&a screen in new tab (+ refactor search profile linking)

chat/application-layer/hooks/online.tsx, chat/application-layer/index.tsx, chat/websocket-layer.tsx, components/avatar.tsx, components/conversation-screen.tsx, components/inbox-item.tsx, components/profile-card.tsx, components/prospect-profile-screen.tsx, constants/constants.tsx, util/util.tsx
Related: https://github.com/duolicious/duolicious-backend/pull/674
=> Add live-updated online status

app.config.ts, package-lock.json, package.json
• Added online status indicators in chat
=> Version 29.2.0

chat/application-layer/hooks/online.tsx
=> Reduce renders in `useOnline`

chat/application-layer/index.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/701
=> Fix: Typing updates the inbox

app.config.ts, package-lock.json, package.json
• Show "[person] is typing..." when chatting
• Bug fixes and performance improvements
=> Version 29.3.0

components/prospect-profile-screen.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/704
=> Add green "online" indicator to profiles above the fold

chat/application-layer/index.tsx
=> Update archived location

app.config.ts, package-lock.json, package.json
• Added "online" indicator to profiles above the fold
• Bug fixes and performance improvements
=> Version 29.3.1

chat/application-layer/index.tsx, components/conversation-screen/conversation-screen.tsx, components/conversation-screen/input.tsx, components/default-text-input.tsx, util/util.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/720
Closes https://github.com/duolicious/duolicious-frontend/issues/725
Closes https://github.com/duolicious/duolicious-frontend/issues/723
=> Random issues

app.config.ts, package-lock.json, package.json
=> Version 29.4.1

components/conversation-screen/conversation-screen.tsx, components/conversation-screen/speech-bubble.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/731
=> Reduce the amount of space taken by the typing indicator

chat/application-layer/index.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/732
=> Fix issue where audio messages aren't displayed until the conversation is reloaded

app.config.ts, package-lock.json, package.json
=> Version 29.4.2

components/conversation-screen/conversation-screen.tsx, components/conversation-screen/message-divider.tsx, components/conversation-screen/speech-bubble.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/736
=> Make the undelivered message opacity lighter

components/audio-player.tsx, util/util.tsx
closes https://github.com/duolicious/duolicious-frontend/issues/740
=> Add loading indicator to audio and prevent pre-downloading

app.config.ts, package-lock.json, package.json
=> Version 29.4.3

app.config.ts, package-lock.json, package.json
=> Version 30.0.1

hide-and-block/hide-and-block.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/773
=> Fix: Skipped profiles can't be visited by URL

components/conversation-screen/quote.test.tsx, components/conversation-screen/quote.tsx, components/error-boundary.tsx, util/util.spec.tsx, util/util.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/779
=> Fix ellipsis in replies

app.config.ts, package-lock.json, package.json
• Added the ability to reply in conversations and the feed
=> Version 30.1.0

app.config.ts, package-lock.json, package.json
=> Version 30.1.1

app.config.ts, package-lock.json, package.json
• Added an extra gender option
• Added a 'recently online' status
=> Version 30.2.0

chat/application-layer/index.tsx, components/conversation-screen/speech-bubble.tsx, components/option-screen.tsx, components/profile-card.tsx, package-lock.json, package.json
=> Support 'Age verification required to chat' message

app.config.ts, package-lock.json, package.json
=> Version 30.4.1

components/feed-tab.tsx
Closes https://github.com/duolicious/duolicious-frontend/issues/843
=> Add a 'was recently online' event to the feed

components/welcome-screen.tsx, kv-storage/upgrade.tsx
To-do:
---
Closes https://github.com/duolicious/duolicious-frontend/issues/848
=> Fix: Accepting an invitation breaks skipping users

components/conversation-screen/quote.test.tsx, components/conversation-screen/quote.tsx, components/conversation-screen/speech-bubble.tsx
=> Make links in chat clickable

components/conversation-screen/quote.tsx
Fixes regression introduced in https://github.com/duolicious/duolicious-frontend/pull/858
=> Undo AI-slopification of `useQuote`

components/feed-tab.tsx
=> Add support for recently online events with photos

app.config.ts, package-lock.json, package.json
• Added an invite button to the search tab
• Recently online members now have specific elements of their bio highlighted in the feed
=> Version 30.6.0

components/welcome-screen.tsx
Merge https://github.com/duolicious/duolicious-frontend/pull/869 first
=> "Your IP address is blocked"

app.config.ts, package-lock.json, package.json
=> Version 30.6.1

components/welcome-screen.tsx
Depends on https://github.com/duolicious/duolicious-backend/pull/822
=> Remove HTTP 403 as indication of being banned

app.config.ts, babel.config.js, components/base-quiz-card.tsx, components/images/images.tsx, package-lock.json, package.json
=> Version 31.1.0

app.config.ts, package-lock.json, package.json
• Profile visitors are now visible
• You can visit invisibly with a new privacy setting
---
=> Version 31.3.0

app.config.ts, package-lock.json, package.json
=> Version 31.3.1

app.config.ts, package-lock.json, package.json
=> Version 31.3.2
