duolicious/duolicious-frontend

components/base-quiz-card.tsx, components/quiz-card-stack.tsx
Fixes an issue in iOS where pull-to-refresh starts happening as someone drags a card.
=> `touchAction: 'none'` on the card stack

components/labelled-slider.tsx, components/option-screen.tsx, components/range-slider.tsx, data/option-groups.tsx, scales/scales.tsx
Distance selection now uses logarithmic scaling. I tested different scaling methods and found that logarithmic scaling with a low base value (<= 2.0) gives the best results. Anything under 2.0 as the base value works fine and tweaking it doesn't make much of a diffference, I went with 1.5 as a good middle ground.
Low distances can now be adjusted with a high precision while high distances have a low precision. I think this is fine since the difference between 9900 and 10000 has a lower significance to users than the difference between 100 and 200, for example.
I implemented this in a way that makes it easy to add other scaling methods to sliders, should they be needed. By default, the old behaviour (linear scaling) is used. I decided not to change the age sliders since linear scaling …
=> #269: Use logarithmic scaling for distance selection

data/option-groups.tsx
At the time of writing, roughly half of users who drop-out of onboarding do so during the first step. The list of gender options might be overwhelming to some and might benefit from being presented differently. In the meanwhile, I've tried adding the name option first, to see if onboardees would be more willing to enter that during the first step, or if it makes them more inclined to continue through onboarding.
Of the users who make it past the gender-related steps, most drop-out when asked for their "First Name". I've changed this to "Display Name".
None of the users who drop out of onboarding included an "about" section. I've removed this requirement from onboarding.
Only about 2% of people who drop out of onboarding bothered adding any images. This onboarding requirement has also been …
=> Simplify onboarding flow

App.tsx, components/conversation-screen.tsx, xmpp/xmpp.tsx
* Formatting
* Remove unused variable (`messages` passed to `Menu`)
* Use XMPP library's online/offline events instead of timeouts to figure out if the user is connected
* Add an online/offline indicator to conversation screens
* Truncate long names in conversation screens with an ellipsis
* Make `maybeLoadNextPage` a bit more sensitive to scrolling near the top
* Fix issue where the bottom of the conversation screen can disappear when offline
* Make the `ActivityIndicator` on the send message button smaller (and therefore appear more centered)
* Do one fetch instead of two when fetching the inbox
* Remove `MaxListenersExceededWarning` that can happen when refreshing very frequently
=> XMPP improvements

App.tsx, components/inbox-tab.tsx, components/stream-error-modal.tsx, xmpp/xmpp.tsx
I suspect that this issue is partly to blame for the poor reliability of chat in Duolicious: https://github.com/xmppjs/xmpp.js/issues/902 I also suspect that the Duolicious chat server's reliability is poor.
In any case, we can probably just add some retries and recreate chat clients when the server comes out of the inactive state.
Changes:
* Increase reconnection delay - This prevents clients from DDoSing the server when it goes down then comes back online. Ideally the XMPP library we use (xmpp.js) would support exponential back-off, but it doesn't.
* Recreate the xmpp.js client when the app comes out of the background state on mobile.
* Show a spinner on the inbox tab when temporarily offline
* Use an application-level ping mechanism to determine if the server can be contacted. This …
=> Attempt to make chat more reliable

components/image-cropper.tsx, components/images.tsx
`Image.getSize` lies sometimes. Worryingly, this issue appears to have been reported to the React Native dev team a few times since 2018, yet no fix is forthcoming: https://github.com/facebook/react-native/issues/22145, https://github.com/facebook/react-native/issues/33498.
Closes https://github.com/duolicious/duolicious-frontend/issues/417.
=> Don't use `Image.getSize`

package-lock.json, package.json
I might add it back later if the funding situation gets dire, but web users are covering server costs for now. Besides, the extra dependency increases the app's download size, and I don't like Google Play indicating that Duolicious has in-app purchases, when it should be more accurately described as an in-app donation method (which hasn't been implemented anyway).
=> Remove RevenueCat

.github/workflows/publish.yml, app.config.ts, components/traits-tab.tsx, env/env.tsx
Currently the share URL domain in the profile is not configurable. This creates a new environment variable and remove the hardcoding.
=> Make Share URL configurable

components/avatar.tsx, components/base-quiz-card.tsx
This fixes two UI/UX bugs:
* c2ef06e2b4f59c7b8b5751f3f0d65538593f97c8 - The `Verify your {verificationRequired} to unlock` message on the Q&A tab appeared on an opaque, square background which didn't line up with the circular avatars it on which is was overlaid. This issue was evident when a Q&A card would move underneath the Avatar.
* 16aa08962544a0e2d1cfa7d4a2ccd33672ed1d59 - The quiz cards would sometimes freeze. There might still be some ways to make the quiz cards freeze, but one underlying issue is that there's an `isAnimating` ref designed to prevent user interaction which wasn't getting reset sometimes. This happened when there was only a very small amount of movement in the quiz card stack. I suspect high DPI devices are worst-affected; There's been a long-lived and steady stream …
=> UI rough edges

components/images/images.tsx
=> React Native reanimated gives warnings about .value being used during render

components/default-flat-list.tsx
#587 might have produced a regression where the search results sometimes appear blank when the user navigates back after viewing a profile.
=> Partially revert #587

components/deafult-modal.tsx, components/donation-nag-modal.tsx, components/report-modal.tsx
The report modal stopped displaying properly in Android recently. I didn't bother tracking down the commit where the regression was introduced, though https://github.com/facebook/react-native/issues/48611 might be the cause; I wrote my own `Modal` and it seems to work fine now :man_shrugging:
=> Fix report modal bug

api/api.tsx, components/base-quiz-card.tsx, components/button/centered-text.tsx
* Fixes #593
* Fixes a regression re-introduced by #591, where users can "catch" a card as it's leaving the screen. This causes the logic and UI to lose sync when answering Q&A questions, resulting in users ostensibly answering one question, but having the app POST it as a response to another question.
=> Card stack bug squashing

components/images/images.tsx, components/profile-tab.tsx
Before this would look awkward, with other text in the same view like "Hold and drag photos" being rendered over the dragged image.
A zIndex of 999 seems arbitrary, but this was also used as a "really high value" in other places already.
Closes #609
---
To do:
=> fix: ensure dragged photos are on top of other elements

components/modal/gif-picker-modal.tsx
Turns out we're legally required to mention Tenor™
=> Tenor attribution

App.tsx, chat/application-layer.tsx, chat/websocket-layer.tsx, components/conversation-screen.tsx, components/inbox-item.tsx, components/inbox-tab.tsx, components/navigation/tab-bar.tsx, components/navigation/web-bar.tsx, components/profile-tab.tsx, data/option-groups.tsx, events/events.tsx, hide-and-block/hide-and-block.tsx, notifications/notifications.tsx, package-lock.json, package.json, util/util.tsx
Loading the inbox takes a lot of CPU time on mobile devices. The lag is noticeable even on high-end android devices (#638). Using JSON rather than XML seems to reduce the lag. I guess the XML parser implementation we're using is much slower than `JSON.parse` and `JSON.stringify`.
Poor performance due to big inboxes disproportionately affects women, so I hope this PR improves the gender ratio.
JS/TS syntax is also such that dealing with JSON is more succinct than XML.
This PR will let us also remove dependencies related to XMPP and XML.
=> Chat via JSON

components/labelled-slider.tsx
Steps to reproduce on web (and probably mobile):
1. Navigate to Search tab > Search Filters > Furthest distance.
2. Without closing the 'Furthest Distance' screen, press the 'Inbox' tab. Open a conversation.
3. Refresh. The app should crash.
Upon inspecting local storage, this is in `navigation_state`:
```
...
"params": {
"optionGroups": [
{
"title": "Furthest Distance",
"description": "How far away can people be?",
"input": {
"slider": {
"sliderMin": 5,
"sliderMax": 10000,
"defaultValue": 10000,
"step": 1,
"unitsLabel": "km",
"addPlusAtMax": true,
"scale": {},
"currentValue": null
}
}
},
...
```
The important part is `"scale": {}`. It seems not to be getting properly serialized.
=> Fix issue with restoring state

components/labelled-slider.tsx
I had to revert #670 because it caused the app to break in the case where `scale` was `undefined`. That case is even more common than the error case I was trying to handle.
The app is still broken, though it's less-broken than it was before. The proper solution is to somehow prevent the 'Furthest Distance' screen from making its way into `navigation_state` as described in #670.
=> Fix issue with restoring state again

api/api.tsx, app.config.ts, package-lock.json, package.json
• Added the Feed
• Removed the "Traits" tab
---
TODO:
=> Version 30.0.0

App.tsx, app.config.ts, components/option-screen.tsx, components/profile-tab.tsx, components/verification-camera.tsx, components/verification-camera/index.tsx, components/verification-camera/resolution.test.tsx, components/verification-camera/resolution.tsx, data/option-groups.tsx, package-lock.json, package.json, verification/verification.tsx
This is the first in a series of PRs which will make verification less prone to spoofing. The current road map includes these milestones:
* Allow submissions via the camera rather than file upload (this PR)
* Add liveness checks (if necessary)
* Require verification for UK users by the deadline
---
TODO:
---
Notes:
- According to expo's performance monitor, the camera takes 223.14 - 218.08 = 5.01 MB of RAM on iOS. I'm sceptical.
=> Verify via camera rather than direct upload

components/image-cropper.tsx, components/verification-camera/index.tsx
* Use safe area view
* Use close button consistent with the rest of the UI
I've also made the back button work for the image picker. Related: https://github.com/duolicious/duolicious-frontend/issues/816
=> Verification UI improvements

components/utility-screen.tsx
An integer overflow issue can allow an attacker to bring down Duolicious by giving a month's worth of donations. Thankfully, we've never received this much.
=> Fix issue with too many donations

api/api.tsx
https://status.duolicious.app/ now yields:
```json
{ "api_version": 6, "statuses": [ "ok", "down for maintenance" ], "status_index": 0 }
```
Support for API v5 is deprecated.
`7` and `700_000` have been added to `SUPPORTED_API_VERSIONS` to support future upgrades.
=> API version 6

animation/animation.tsx, components/navigation/tab-bar.tsx
Buttons which use `usePressableAnimation` to animate their presses can flicker when the user releases the button very shortly after pressing it.
=> Fix button flicker
